## -- STD LIB IMPORTS --
import os

## -- CONSTANTS --
# ISO 3166-1 alpha-2 country codes for UN 193 countries + 2 observer states
# @TODO: At some point remove all the countries that do not have an iTunes store front
ISO_3166_1_ALPHA_2_CC = {
    "Afghanistan": "af",
    "Albania": "al",
    "Algeria": "dz",
    "Andorra": "ad",
    "Angola": "ao",
    "Antigua and Barbuda": "ag",
    "Argentina": "ar",
    "Armenia": "am",
    "Australia": "au",
    "Austria": "at",
    "Azerbaijan": "az",
    "Bahamas": "bs",
    "Bahrain": "bh",
    "Bangladesh": "bd",
    "Barbados": "bb",
    "Belarus": "by",
    "Belgium": "be",
    "Belize": "bz",
    "Benin": "bj",
    "Bhutan": "bt",
    "Bolivia, Plurinational State of": "bo",
    "Bosnia and Herzegovina": "ba",
    "Botswana": "bw",
    "Brazil": "br",
    "Brunei Darussalam": "bn",
    "Bulgaria": "bg",
    "Burkina Faso": "bf",
    "Burundi": "bi",
    "Cabo Verde": "cv",
    "Cambodia": "kh",
    "Cameroon": "cm",
    "Canada": "ca",
    "Central African Republic": "cf",
    "Chad": "td",
    "Chile": "cl",
    "China": "cn",
    "Colombia": "co",
    "Comoros": "km",
    "Congo": "cg",
    "Congo, Democratic Republic of the": "cd",
    "Costa Rica": "cr",
    "Cote d'Ivoire": "ci",
    "Croatia": "hr",
    "Cuba": "cu",
    "Cyprus": "cy",
    "Czechia": "cz",
    "Denmark": "dk",
    "Djibouti": "dj",
    "Dominica": "dm",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "Egypt": "eg",
    "El Salvador": "sv",
    "Equatorial Guinea": "gq",
    "Eritrea": "er",
    "Estonia": "ee",
    "Eswatini": "sz",
    "Ethiopia": "et",
    "Fiji": "fj",
    "Finland": "fi",
    "France": "fr",
    "Gabon": "ga",
    "Gambia": "gm",
    "Georgia": "ge",
    "Germany": "de",
    "Ghana": "gh",
    "Greece": "gr",
    "Grenada": "gd",
    "Guatemala": "gt",
    "Guinea": "gn",
    "Guinea-Bissau": "gw",
    "Guyana": "gy",
    "Haiti": "ht",
    "Holy See, (the)": "va",
    "Honduras": "hn",
    "Hungary": "hu",
    "Iceland": "is",
    "India": "in",
    "Indonesia": "id",
    "Iran, Islamic Republic of": "ir",
    "Iraq": "iq",
    "Ireland": "ie",
    "Israel": "il",
    "Italy": "it",
    "Jamaica": "jm",
    "Japan": "jp",
    "Jordan": "jo",
    "Kazakhstan": "kz",
    "Kenya": "ke",
    "Kiribati": "ki",
    "Korea, Democratic People's Republic of": "kp",
    "Korea, Republic of": "kr",
    "Kuwait": "kw",
    "Kyrgyzstan": "kg",
    "Lao People's Democratic Republic": "la",
    "Latvia": "lv",
    "Lebanon": "lb",
    "Lesotho": "ls",
    "Liberia": "lr",
    "Libya": "ly",
    "Liechtenstein": "li",
    "Lithuania": "lt",
    "Luxembourg": "lu",
    "Madagascar": "mg",
    "Malawi": "mw",
    "Malaysia": "my",
    "Maldives": "mv",
    "Mali": "ml",
    "Malta": "mt",
    "Marshall Islands": "mh",
    "Mauritania": "mr",
    "Mauritius": "mu",
    "Mexico": "mx",
    "Micronesia, Federated States of": "fm",
    "Moldova, Republic of": "md",
    "Monaco": "mc",
    "Mongolia": "mn",
    "Montenegro": "me",
    "Morocco": "ma",
    "Mozambique": "mz",
    "Myanmar": "mm",
    "Namibia": "na",
    "Nauru": "nr",
    "Nepal": "np",
    "Netherlands": "nl",
    "New Zealand": "nz",
    "Nicaragua": "ni",
    "Niger": "ne",
    "Nigeria": "ng",
    "North Macedonia": "mk",
    "Norway": "no",
    "Oman": "om",
    "Pakistan": "pk",
    "Palau": "pw",
    "Palestine, State of": "ps",
    "Panama": "pa",
    "Papua New Guinea": "pg",
    "Paraguay": "py",
    "Peru": "pe",
    "Philippines": "ph",
    "Poland": "pl",
    "Portugal": "pt",
    "Qatar": "qa",
    "Romania": "ro",
    "Russian Federation": "ru",
    "Rwanda": "rw",
    "Saint Kitts and Nevis": "kn",
    "Saint Lucia": "lc",
    "Saint Vincent and the Grenadines": "vc",
    "Samoa": "ws",
    "San Marino": "sm",
    "Sao Tome and Principe": "st",
    "Saudi Arabia": "sa",
    "Senegal": "sn",
    "Serbia": "rs",
    "Seychelles": "sc",
    "Sierra Leone": "sl",
    "Singapore": "sg",
    "Slovakia": "sk",
    "Slovenia": "si",
    "Solomon Islands": "sb",
    "Somalia": "so",
    "South Africa": "za",
    "South Sudan": "ss",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Sudan": "sd",
    "Suriname": "sr",
    "Sweden": "se",
    "Switzerland": "ch",
    "Syrian Arab Republic": "sy",
    "Tajikistan": "tj",
    "Tanzania, United Republic of": "tz",
    "Thailand": "th",
    "Timor-Leste": "tl",
    "Togo": "tg",
    "Tonga": "to",
    "Trinidad and Tobago": "tt",
    "Tunisia": "tn",
    "Türkiye": "tr",
    "Turkmenistan": "tm",
    "Tuvalu": "tv",
    "Uganda": "ug",
    "Ukraine": "ua",
    "United Arab Emirates": "ae",
    "United Kingdom of Great Britain and Northern Ireland": "gb",
    "United States of America": "us",
    "Uruguay": "uy",
    "Uzbekistan": "uz",
    "Vanuatu": "vu",
    "Venezuela, Bolivarian Republic of": "ve",
    "Viet Nam": "vn",
    "Yemen": "ye",
    "Zambia": "zm",
    "Zimbabwe": "zw"
}

# Weighted RGB to Luminance conversion weights
LUMINANCE_WEIGHTS = [0.2126, 0.7152, 0.0722]

# iTunes API base URLs
SEARCH_API_BASE_URL = "https://itunes.apple.com/search"
LOOKUP_API_BASE_URL = 'https://itunes.apple.com/lookup'

# API album entity return limit
ALBUM_RESULT_LIMIT = 5

# Temporary artwork file path
TEMP_ARTWORK_DIR_PATH = os.path.join(".", ".temp") 
TEMP_ARTWORK_FILE_NAME = "artwork.jpg"

# Template option file paths
TEMPLATE_OPTIONS = {
    "Classic": os.path.join(".", "templates", "classic", "classic.json")
}

# Output folder directory path
OUTPUT_FOLDER = os.path.join(".", "out")

# Terminal color formatting ANSI escape codes
# Reference: https://en.wikipedia.org/wiki/ANSI_escape_code
ANSI_FORMATS = {
    "FONT_BLACK": "\033[0;30m",
    "FONT_RED": "\033[0;31m",
    "FONT_GREEN": "\033[0;32m",
    "FONT_BROWN": "\033[0;33m",
    "FONT_BLUE": "\033[0;34m",
    "FONT_PURPLE": "\033[0;35m",
    "FONT_CYAN": "\033[0;36m",
    "FONT_LIGHT_GRAY": "\033[0;37m",
    "FONT_DARK_GRAY": "\033[1;30m",
    "FONT_LIGHT_RED": "\033[1;31m",
    "FONT_LIGHT_GREEN": "\033[1;32m",
    "FONT_YELLOW": "\033[1;33m",
    "FONT_LIGHT_BLUE": "\033[1;34m",
    "FONT_LIGHT_PURPLE": "\033[1;35m",
    "FONT_LIGHT_CYAN": "\033[1;36m",
    "FONT_LIGHT_WHITE": "\033[1;37m",
    "FONT_BOLD": "\033[1m",
    "FONT_FAINT": "\033[2m",
    "FONT_ITALIC": "\033[3m",
    "FONT_UNDERLINE": "\033[4m",
    "FONT_BLINK": "\033[5m",
    "FONT_NEGATIVE": "\033[7m",
    "FONT_CROSSED": "\033[9m",
    "END": "\033[0m"
}